### ISSUE TITLE
Change to `fix` callback

### ISSUE THREAD

**Issue by sean-redteam** [jeddy3/stylelint-scales#98]
### What steps are needed to reproduce the bug?

1. Enable stylelint in WebStorm.
2. Add any `stylelint-scales` rules to stylelintrc file.
Example from my project:
```
"scales/font-sizes": [
  { "scale":  [1, 1,5, 2], "units":  ["rem"] }
]
```
3. Open any CSS file to trigger Stylelint check

### What did you expect to happen?

Stylelint runs and reports errors

### What actually happened?

Two things:
1. Warning banner about `context.fix` being deprecated
Full error:
```
(node:21830) [stylelint:005] DeprecationWarning: `context.fix` is being deprecated.
Please pass a `fix` callback to the `report` utility of "scales/font-sizes" instead.
```
2. Stylelint fails to run

**Comment by sean-redteam** [comment]
The form doesn't allow for additional context, so first off, thanks for creating this plugin.

I did some investigation. It looks like the rules just need a small update to stop using the context object for autofixing and instead passing the `fix` callback to the report call.

Old:
```
const rule = (primary, secondary, { fix }) => {
  return (root, result) => {
    ...

        if (fix) {
          node.value = getClosest(scale, value);
          hasFix = true;
          return;
        }

        report({
          message: messages.expected(value, scale.join(", "), unit),
          node: decl,
          result,
          ruleName,
          word: value,
        });

      if (hasFix) setValue(decl, valueRoot.toString());
    });
  };
};
```

New:
```
const rule = (primary, secondary) => {
  return (root, result) => {
    ...

        report({
         fix: () => {
            node.value = getClosest(scale, value);
            hasFix = true;
            return;
          },
          message: messages.expected(value, scale.join(", "), unit),
          node: decl,
          result,
          ruleName,
          word: value,
        });
    });
  };
};
```

I'm not sure about is the last line though:
```
 if (hasFix) setValue(decl, valueRoot.toString());
```

I'm happy to create a PR to update the rules if someone else doesn't have the bandwidth. I'll just turn the rule off until it's fix.

Thanks!

**Comment by jeddy3** [comment]
@sean-redteam Thank you for the report and for investigating. 

> I'm happy to create a PR to update the rules if someone else doesn't have the bandwidth. I'll just turn the rule off until it's fix.

That'd be fantastic, thank you! 

> I'm not sure about is the last line though: `if (hasFix) setValue(decl, valueRoot.toString());`

That's doing the mutation, so I assume it'll go in the `fix` callback, too? There's a brief write-up from another plugin author here that may give us some pointers: https://github.com/stylelint/stylelint/issues/7788#issuecomment-2299705237

**Comment by sean-redteam** [comment]
Awesome! Sounds great! I've been looking for a weekend project. I now have one.
